stages:
    - build
    - test
build:
  stage: build
  script: 'make'
valid-tests:
  stage: test
  script: 'bash test.sh valid'
syntax-tests:
  stage: test
  script: 'bash test.sh syntax_err'
semantic-tests:
  stage: test
  script: 'bash test.sh semantic_err'