stages:
    - build
    - test
build:
  stage: build
  script: 'mvn package'
valid-tests:
  stage: test
  script: 'sh test.sh valid'
syntax-tests:
  stage: test
  script: 'sh test.sh syntax_err'
semantic-tests:
  stage: test
  script: 'sh test.sh semantic_err'