#!/bin/sh
# Ruby front-end for your compiler.
# You are free to change the language used for this script,
# but do *not* change its name.

# puts "TODO: setup this script to call your WACC compiler"

TARGET=./target/wacc_25-1.0-jar-with-dependencies.jar

java -jar $TARGET $1 < $1
exit $?
